//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M13TipusHab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class costa
    {
        public int TipusHab_codi { get; set; }
        public int Tarifa_codi { get; set; }
        public Nullable<decimal> preu { get; set; }
        public System.DateTime DesDe { get; set; }
        public Nullable<System.DateTime> FinsA { get; set; }
    
        public virtual tarifa tarifa { get; set; }
        public virtual tipusHab tipusHab { get; set; }
    }
}
