//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M13TipusHab.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hotelEntities : DbContext
    {
        public hotelEntities()
            : base("name=hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calendari> calendaris { get; set; }
        public virtual DbSet<costa> costas { get; set; }
        public virtual DbSet<costaDia> costaDias { get; set; }
        public virtual DbSet<habitacio> habitacios { get; set; }
        public virtual DbSet<habitacioDia> habitacioDias { get; set; }
        public virtual DbSet<reserva> reservas { get; set; }
        public virtual DbSet<tarifa> tarifas { get; set; }
        public virtual DbSet<tipusBalco> tipusBalcoes { get; set; }
        public virtual DbSet<TipusHab> tipusHabs { get; set; }
    
        public virtual int addDates(Nullable<System.DateTime> dataInici, Nullable<System.DateTime> dataFi)
        {
            var dataIniciParameter = dataInici.HasValue ?
                new ObjectParameter("dataInici", dataInici) :
                new ObjectParameter("dataInici", typeof(System.DateTime));
    
            var dataFiParameter = dataFi.HasValue ?
                new ObjectParameter("dataFi", dataFi) :
                new ObjectParameter("dataFi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addDates", dataIniciParameter, dataFiParameter);
        }
    
        public virtual int addCosta0(Nullable<System.DateTime> dataInici)
        {
            var dataIniciParameter = dataInici.HasValue ?
                new ObjectParameter("dataInici", dataInici) :
                new ObjectParameter("dataInici", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addCosta0", dataIniciParameter);
        }
    }
}
