//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M13TipusHab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.habitacioDias = new HashSet<habitacioDia>();
        }
    
        public int codi { get; set; }
        public System.DateTime dataReserva { get; set; }
        public System.DateTime dataInPrev { get; set; }
        public Nullable<System.DateTime> dataInReal { get; set; }
        public Nullable<System.DateTime> dataOutPrev { get; set; }
        public Nullable<System.DateTime> dataOutReal { get; set; }
        public Nullable<System.DateTime> dataCancel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<habitacioDia> habitacioDias { get; set; }
    }
}
