//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M13TipusHab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipusHab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipusHab()
        {
            this.costas = new HashSet<costa>();
            this.costaDias = new HashSet<costaDia>();
            this.habitacios = new HashSet<habitacio>();
        }
    
        public int codi { get; set; }
        public string nom { get; set; }
        public short llitsInd { get; set; }
        public short llitsDob { get; set; }
        public Nullable<short> qntPersones { get; set; }
        public string tipusBalco { get; set; }
        public Nullable<short> teBanyera { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costa> costas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<costaDia> costaDias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<habitacio> habitacios { get; set; }
        public virtual tipusBalco tipusBalco1 { get; set; }
    }
}
